@echo off
setlocal enabledelayedexpansion

REM ============================================
REM init_build.bat  -  KForge C++20 Modules Build
REM
REM   Framework (modules/cpp/*.ixx) + test/ are built via CMake.
REM   Build output: build-msvc\ (objs) and <root>\Release\*.exe.
REM
REM   Modes:
REM     (no arg)      Configure + build module library (.ixx) + generate build.bat scripts.
REM                   init_build 集始化：编译模块库；不编译 cpp，不改动 Release.
REM     --config      Configure only (build-msvc + VS generator)
REM     --build       Explicit: build all modules + test exes (only when requested)
REM     --setup       MSVC environment only (for legacy manual cl)
REM     --ide         Generate build-ide\compile_commands.json only (VS Code IntelliSense).
REM                   No compilation, no changes to modules/ or Release.
REM ============================================

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"

if "%~1"=="--setup"   goto :msvc_setup
if "%~1"=="--config"  goto :do_configure
if "%~1"=="--build"   goto :do_build
if "%~1"=="--ide"     goto :do_ide

echo ============================================
echo   KForge - Init Build (C++20 Modules / CMake)
echo ============================================
echo.

REM init_build 负责配置 CMake并编译模块库 (.ixx → KF.lib/.ifc) 完成初始化，
REM 再生成各目录 build.bat；build.bat 只编译并链接程序 (.cpp)。

echo [1/4] Configure CMake (build-msvc) ...
call :do_configure
if errorlevel 1 goto :err
echo       Done.
echo.
echo [2/4] Build module library (init_build 初始化/编译模块) ...
call :do_build_modules
if errorlevel 1 goto :err
echo       Done.
echo.
echo [3/4] Generate test\build.bat ...
call :write_test_build_bat
echo       Done.
echo.
echo [4/4] Generate study\ build.bat (self-contained) ...
call :gen_scripts "%ROOT%\study"
echo       Done.
echo.
echo ============================================
echo   Done. init_build 已编译模块库 (KF.lib / .ifc)，
echo   未编译任何 cpp，Release 均未被改动。
echo   Run <dir>\build.bat to compile & link programs.
echo ============================================
pause
goto :end

REM ========== :do_configure ==========
:do_configure
where cmake >nul 2>nul
if errorlevel 1 (
    echo [ERROR] cmake not found in PATH
    exit /b 1
)
cmake -S "%ROOT%" -B "%ROOT%\build-msvc" -G "Visual Studio 17 2022" -A x64
exit /b %errorlevel%

REM ========== :do_build_modules - 编译模块库 (init_build 初始化) ==========
:do_build_modules
if not exist "%ROOT%\build-msvc\CMakeCache.txt" (
    echo [ERROR] build-msvc not configured. Run init_build.bat --config first.
    exit /b 1
)
cmake --build "%ROOT%\build-msvc" --config Release --target kf kmath
exit /b %errorlevel%

REM ========== :do_build ==========
:do_build
if not exist "%ROOT%\build-msvc\CMakeCache.txt" (
    echo [ERROR] build-msvc not configured. Run init_build.bat --config first.
    exit /b 1
)
cmake --build "%ROOT%\build-msvc" --config Release
exit /b %errorlevel%

REM ========== :do_ide - generate compile_commands.json for IntelliSense ==========
REM   仅做 Ninja 配置以产出 build-ide\compile_commands.json，
REM   不编译任何 cpp，不写入/删除 modules/ 或 Release。
:do_ide
call :msvc_setup
if errorlevel 1 exit /b 1
set "NINJA=%VSROOT%\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
if not exist "%NINJA%" (
    for /r "%VSROOT%" %%f in (ninja.exe) do if exist "%%f" set "NINJA=%%f"
)
if not exist "%NINJA%" (
    echo [ERROR] ninja not found. Install VS 2022 CMake/Ninja component.
    exit /b 1
)
if exist "%ROOT%\build-ide" rd /s /q "%ROOT%\build-ide"
cmake -S "%ROOT%" -B "%ROOT%\build-ide" -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=cl -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY -DCMAKE_MAKE_PROGRAM="%NINJA%"
if errorlevel 1 exit /b 1
echo.
echo   IntelliSense compile database: %ROOT%\build-ide\compile_commands.json
echo   (仅生成数据库，未编译 cpp)
exit /b 0

REM ========== :write_test_build_bat ==========
:write_test_build_bat
set "out=%ROOT%\test\build.bat"
setlocal disabledelayedexpansion
> "%out%" echo @echo off
>>"%out%" echo setlocal
>>"%out%" echo REM Auto-generated by init_build.bat - self-contained; builds all test exes via CMake
>>"%out%" echo for %%%%I in ("%%~dp0..") do set "ROOT=%%%%~fI"
>>"%out%" echo.
>>"%out%" echo if not exist "%%ROOT%%\build-msvc\CMakeCache.txt" (
>>"%out%" echo     cmake -S "%%ROOT%%" -B "%%ROOT%%\build-msvc" -G "Visual Studio 17 2022" -A x64
>>"%out%" echo     if errorlevel 1 goto :err
>>"%out%" echo )
>>"%out%" echo cmake --build "%%ROOT%%\build-msvc" --config Release
>>"%out%" echo if errorlevel 1 goto :err
>>"%out%" echo echo.
>>"%out%" echo echo [DONE] Test executables: "%%ROOT%%\test\Release\"
>>"%out%" echo pause
>>"%out%" echo goto :end
>>"%out%" echo.
>>"%out%" echo :err
>>"%out%" echo echo [ERROR] Build failed.
>>"%out%" echo pause
>>"%out%" echo exit /b 1
>>"%out%" echo.
>>"%out%" echo :end
>>"%out%" echo endlocal
>>"%out%" echo exit /b 0
endlocal
exit /b 0

REM ========== :msvc_setup - MSVC env only (vswhere, no hardcoded paths) ==========
:msvc_setup
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" set "VSWHERE=%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe"
if not exist "%VSWHERE%" (
    echo [ERROR] vswhere.exe not found - install VS 2022
    exit /b 1
)
for /f "usebackq delims=" %%i in (`"%VSWHERE%" -latest -property installationPath`) do set "VSROOT=%%i"
if not defined VSROOT (
    echo [ERROR] VS installation not found (vswhere)
    exit /b 1
)
set "VCVARS=%VSROOT%\VC\Auxiliary\Build\vcvarsall.bat"
if not exist "%VCVARS%" (
    echo [ERROR] vcvarsall.bat not found: %VCVARS%
    exit /b 1
)
call "%VCVARS%" x64 >nul 2>nul
exit /b %errorlevel%

REM ========== :gen_scripts - recursive (active dirs only) ==========
:gen_scripts
set "dir=%~1"
echo !dir! | findstr /i "\\legacy" >nul 2>nul
if not errorlevel 1 exit /b 0
set "has=0"
for %%f in ("%dir%\*.cpp") do set "has=1"
if "!has!"=="1" (
    call :write_build_bat  "%dir%"
    echo   [GEN] %dir%\build.bat
)
for /d %%d in ("%dir%\*") do call :gen_scripts "%%d"
exit /b 0

REM ========== :write_build_bat - plain cl (no KF.lib) ==========
REM   %1 = target directory
:write_build_bat
set "dir=%~1"
set "rel=%dir%"
set "rel=!rel:%ROOT%\=!"
set "to_root="
:rel_loop
if "!rel!"=="" goto :rel_end
set "to_root=!to_root!..\"
set "part=!rel:*\=!"
if "!part!"=="!rel!" (set "rel=") else (set "rel=!part!")
goto :rel_loop
:rel_end
set "out=%dir%\build.bat"
setlocal disabledelayedexpansion

> "%out%" echo @echo off
>>"%out%" echo setlocal enabledelayedexpansion
>>"%out%" echo.
>>"%out%" echo REM Auto-generated by init_build.bat - self-contained (no KF, no init_build)
>>"%out%" echo set "DIR=%%~dp0"
>>"%out%" echo set "DIR=!DIR:~0,-1!"
>>"%out%" echo call :msvc
>>"%out%" echo if errorlevel 1 exit /b 1
>>"%out%" echo set "CXXFLAGS=/O2 /std:c++20 /utf-8 /EHsc /MD"
>>"%out%" echo set "LINKFLAGS=/OPT:REF /OPT:ICF /SUBSYSTEM:CONSOLE"
>>"%out%" echo.
>>"%out%" echo set "filecount=0"
>>"%out%" echo for %%%%f in ("!DIR!\*.cpp") do (
>>"%out%" echo     set /a filecount+=1
>>"%out%" echo     set "file_!filecount!=%%%%~nxf"
>>"%out%" echo     set "filepath_!filecount!=%%%%f"
>>"%out%" echo )
>>"%out%" echo.
>>"%out%" echo if "!filecount!"=="0" (
>>"%out%" echo     echo No .cpp files found.
>>"%out%" echo     pause
>>"%out%" echo     exit /b 0
>>"%out%" echo )
>>"%out%" echo.
>>"%out%" echo echo   Files in this directory:
>>"%out%" echo for /l %%%%i in (1,1,!filecount!) do echo     %%%%i. !file_%%%%i!
>>"%out%" echo set "choice="
>>"%out%" echo set /p "choice=  Select numbers (e.g. 1 3) or Enter for all: "
>>"%out%" echo.
>>"%out%" echo if not exist "!DIR!\Release" mkdir "!DIR!\Release"
>>"%out%" echo set "compileall=1"
>>"%out%" echo if defined choice (
>>"%out%" echo     set "sel=!choice:,= !"
>>"%out%" echo     set "seltrimmed=!sel: =!"
>>"%out%" echo     if not "!seltrimmed!"=="" set "compileall=0"
>>"%out%" echo )
>>"%out%" echo if "!compileall!"=="1" (
>>"%out%" echo     for /l %%%%i in (1,1,!filecount!) do (
>>"%out%" echo         call :compile_one "!filepath_%%%%i!" "!file_%%%%i:~0,-4!"
>>"%out%" echo         if errorlevel 1 goto :build_err
>>"%out%" echo     )
>>"%out%" echo ) else (
>>"%out%" echo     for %%%%n in (!sel!) do (
>>"%out%" echo         if defined filepath_%%%%n (
>>"%out%" echo             call :compile_one "!filepath_%%%%n!" "!file_%%%%n:~0,-4!"
>>"%out%" echo             if errorlevel 1 goto :build_err
>>"%out%" echo         ) else (
>>"%out%" echo             echo   [WARN] Invalid: %%%%n
>>"%out%" echo         )
>>"%out%" echo     )
>>"%out%" echo )
>>"%out%" echo.
>>"%out%" echo echo   [DONE] Build complete. Output: !DIR!\Release\
>>"%out%" echo pause
>>"%out%" echo goto :build_end
>>"%out%" echo.
>>"%out%" echo :msvc
>>"%out%" echo set "VSWHERE=%%ProgramFiles(x86)%%\Microsoft Visual Studio\Installer\vswhere.exe"
>>"%out%" echo if not exist "%%VSWHERE%%" set "VSWHERE=%%ProgramFiles%%\Microsoft Visual Studio\Installer\vswhere.exe"
>>"%out%" echo if not exist "%%VSWHERE%%" goto :msvc_err
>>"%out%" echo for /f "usebackq delims=" %%%%i in (`"%%VSWHERE%%" -latest -property installationPath`) do set "VSROOT=%%%%i"
>>"%out%" echo if not defined VSROOT goto :msvc_err
>>"%out%" echo set "VCVARS=%%VSROOT%%\VC\Auxiliary\Build\vcvarsall.bat"
>>"%out%" echo if not exist "%%VCVARS%%" goto :msvc_err
>>"%out%" echo call "%%VCVARS%%" x64 ^>nul 2^>nul
>>"%out%" echo if errorlevel 1 goto :msvc_err
>>"%out%" echo exit /b 0
>>"%out%" echo :msvc_err
>>"%out%" echo echo [ERROR] MSVC (vswhere.exe / vcvarsall.bat) not found
>>"%out%" echo exit /b 1
>>"%out%" echo.
>>"%out%" echo :compile_one
>>"%out%" echo set "cf=%%~1"
>>"%out%" echo set "cn=%%~2"
>>"%out%" echo REM 先删旧文件再编译
>>"%out%" echo del /q "!DIR!\Release\!cn!.exe" 2^>nul
>>"%out%" echo del /q "!DIR!\Release\!cn!.obj" 2^>nul
>>"%out%" echo echo   [BUILD] !cn!.cpp
>>"%out%" echo cl /c !CXXFLAGS! "!cf!" /Fo:"!DIR!\Release\!cn!.obj"
>>"%out%" echo if errorlevel 1 (
>>"%out%" echo     echo   [FAIL] !cn!.cpp - compile error
>>"%out%" echo     exit /b 1
>>"%out%" echo )
>>"%out%" echo link !LINKFLAGS! "!DIR!\Release\!cn!.obj" /out:"!DIR!\Release\!cn!.exe"
>>"%out%" echo if errorlevel 1 (
>>"%out%" echo     echo   [FAIL] !cn!.cpp - link error
>>"%out%" echo     exit /b 1
>>"%out%" echo )
>>"%out%" echo del "!DIR!\Release\!cn!.obj"
>>"%out%" echo echo   [OK] !cn!.cpp
>>"%out%" echo exit /b 0
>>"%out%" echo.
>>"%out%" echo :build_err
>>"%out%" echo echo   [ERROR] Build failed.
>>"%out%" echo pause
>>"%out%" echo exit /b 1
>>"%out%" echo.
>>"%out%" echo :build_end
>>"%out%" echo endlocal
>>"%out%" echo exit /b 0
endlocal
exit /b 0

REM ========== error / end ==========
:err
echo [ERROR] Task failed.
pause
exit /b 1

:end
endlocal
exit /b 0